In [23]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import pandas as pd
import warnings

from ipywidgets import widgets
from IPython.html.widgets import *

warnings.filterwarnings('ignore')
rcParams.update({'font.size': 15})
#plt.style.use('ggplot')
#plt.style.use('seaborn-dark-palette')
plt.style.use('fivethirtyeight')

In [24]:
#bear, bunny, green, squid

TASKS = 4
USERS = 5


def stringToInt(arr, position, values):
    for i, v in enumerate(values):
        arr[arr[:,position] == v, position] = i
    return arr


csvFile = '../data/test.csv'
csvFile = '../data/monsters_data_pilot_041417.csv'
csv = np.genfromtxt(csvFile, dtype=np.string_, delimiter=',', usecols=(0,5,6,9), skip_header=1)

#print(csv)

# Get monster type
monsters = [m for m in np.unique(csv[:,1])]
# Get category
#categories = [c for c in np.unique(csv[:,2])]
categories = [b'category1D', b'categoryIgnore1D', b'category2D', b'categoryRandom']
# Get ids
ids = [i for i in np.unique(csv[:,0]) ]
# For converting string to int boolean
bo = [b'False', b'True']

csvInt = csv.copy()
# Convert fields to ints for easy processing
for i,j in enumerate([ids, monsters, categories, bo]):
    csvInt = stringToInt(csvInt, i, j)
csvInt = csvInt.astype('int')

#print(csvInt)

# Split by user
splitCsv = [csvInt[csvInt[:,0]==i] for i in np.unique(csvInt[:,0])]

# Count times correct per task, times task chosen, % for both
metricsUser = []

# id, monster, category, success
for user in range(np.shape(splitCsv)[0]):
    questions = splitCsv[user]
    print(questions)
    # Count number of times a task was selected
    task, ctask = np.unique(questions[:,2], return_counts=True)
    print(task, ctask, ctask/np.shape(questions)[0])
    
    metricsTask = []
    # Count number of times the answer was correct per task and percent
    for t in range(TASKS):
        correct = np.sum(questions[questions[:,2] == t,3] == 1) 
        total = np.sum(questions[:,2] == t)
        if t in task:
            # Task category, times task selected, % selection, #times correct on this task, % correct
            metricsTask.append([user, t, ctask[np.where(task==t)][0], ctask[np.where(task==t)][0]/np.shape(questions)[0], correct, np.nan_to_num(correct/total)])
            #print(t, ctask[np.where(task==t)][0], ctask[np.where(task==t)][0]/np.shape(questions)[0], correct, np.nan_to_num(correct/total) )
        else:
            metricsTask.append([user, t, 0., 0., correct, np.nan_to_num(correct/total)])
            #print(t, 0, 0, correct, np.nan_to_num(correct/total))
            
    metricsUser.append(metricsTask)

print(monsters, categories)
print(metricsUser)


[[0 0 2 0]
 [0 0 2 1]
 [0 0 2 0]
 ..., 
 [0 3 3 1]
 [0 3 3 0]
 [0 3 3 1]]
[0 1 2 3] [ 89  90 153 135] [ 0.19  0.19  0.33  0.29]
[[1 2 2 0]
 [1 2 2 0]
 [1 2 2 1]
 ..., 
 [1 2 2 0]
 [1 2 2 1]
 [1 2 2 1]]
[0 1 2 3] [ 49  32 182 107] [ 0.13  0.09  0.49  0.29]
[[2 0 0 1]
 [2 0 0 0]
 [2 0 0 0]
 [2 0 0 0]
 [2 0 0 0]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0 0]
 [2 0 0 0]
 [2 3 1 1]
 [2 3 1 0]
 [2 3 1 1]
 [2 3 1 0]
 [2 3 1 0]
 [2 3 1 0]
 [2 1 3 1]
 [2 1 3 1]
 [2 1 3 1]
 [2 1 3 0]
 [2 1 3 1]
 [2 1 3 0]
 [2 1 3 1]
 [2 1 3 0]
 [2 2 2 1]
 [2 2 2 0]
 [2 2 2 1]
 [2 2 2 1]
 [2 2 2 0]
 [2 2 2 0]
 [2 2 2 0]
 [2 0 0 0]
 [2 0 0 1]
 [2 0 0 1]
 [2 3 1 1]
 [2 3 1 1]
 [2 3 1 1]
 [2 3 1 0]
 [2 3 1 1]
 [2 3 1 0]
 [2 3 1 1]
 [2 3 1 0]
 [2 1 3 0]
 [2 1 3 0]
 [2 1 3 1]
 [2 1 3 0]
 [2 1 3 1]
 [2 1 3 0]
 [2 1 3 0]
 [2 1 3 0]
 [2 2 2 0]
 [2 2 2 0]
 [2 2 2 1]
 [2 2 2 0]
 [2 2 2 0]
 [2 2 2 1]
 [2 2 2 0]
 [2 0 0 1]
 [2 0 0 0]
 [2 0 0 0]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0 0]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0 1]
 [2 0 0

In [25]:
# participant:assignmentId,interested-Bear,complex-Bear,time-Bear,progress-Bear,learning-Bear,
# rule-Bear,interested-Bunny,complex-Bunny,time-Bunny,progress-Bunny,learning-Bunny,rule-Bunny,
# interested-GreenMonster,complex-GreenMonster,time-GreenMonster,progress-GreenMonster,learning-GreenMonster,
# rule-GreenMonster,interested-Squid,complex-Squid,time-Squid,progress-Squid,learning-Squid,rule-Squid,age,
# gender,race,ethnicity,thoughts,comments

#bear 1:6
#bunny 7:12
#greenm 13:18
#squid 19:24

# Subjective data
csvFile = '../data/monsters_extra_data_pilot_041417.csv'
scsv = np.genfromtxt(csvFile, dtype=np.string_, delimiter=',', skip_header=1)#usecols=(0,5,6,9), skip_header=1)
print(scsv[1])

#Reorder them according to the actual categories
print(monsters, categories)

postCsv = []
for user in range(np.shape(splitCsv)[0]):
    questions = splitCsv[user][:,1:3]
    postQ = scsv[user]
    _, mIdx = np.unique(questions[:,0], return_index=True)
    _, cIdx = np.unique(questions[:,0], return_index=True)
    print(questions[np.sort(mIdx),0])
    print(questions[np.sort(cIdx),1])
    # stack monster type, complexity type
    moncat = np.vstack((questions[np.sort(mIdx),0], questions[np.sort(cIdx),1])).T
    moncat = moncat[moncat[:,0].argsort()]
    print(moncat)
    for n, mon in enumerate(moncat[:,0]):
        answ = postQ[n*6+1:6*(n+1)+1]
        # stack user id, monster id, category id, answers for that category
        print(np.hstack((user, mon, moncat[n,1], answ.tolist())))
        postCsv.append(np.hstack((user, mon, moncat[n,1], answ.tolist())).tolist())
    print(questions)
print(postCsv)

[b'A1GXFMAC759VRM:3DZQRBDBSMUVNJM9G7WCF5YEZIU3SE' b'10' b'10' b'10' b'1'
 b'none' b'unsure' b'5' b'4' b'4' b'10' b'insight' b'yes-rule' b'9' b'9'
 b'10' b'10' b'insight' b'yes-rule' b'2' b'1' b'3' b'10' b'insight'
 b'yes-rule' b'39' b'male' b'white' b'nonhisp'
 b'Intuitive learning about categories' b'NA']
[b'Bear', b'Bunny', b'GreenMonster', b'Squid'] [b'category1D', b'categoryIgnore1D', b'category2D', b'categoryRandom']
[0 2 3 1]
[2 0 3 1]
[[0 2]
 [1 1]
 [2 0]
 [3 3]]
[b'0' b'0' b'2' b'7' b'5' b'5' b'9' b'gradual' b'yes-rule']
[b'0' b'1' b'1' b'6' b'1' b'4' b'10' b'insight' b'yes-rule']
[b'0' b'2' b'0' b'6' b'1' b'4' b'10' b'insight' b'yes-rule']
[b'0' b'3' b'3' b'9' b'10' b'7' b'2' b'none' b'unsure']
[[0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]


In [26]:
postCsv = np.asarray(postCsv)
print(postCsv)
print(np.shape(postCsv))

learnQuest = [i for i in np.unique(postCsv[:,-2]) ]
print(learnQuest)
ruleQuest = [i for i in np.unique(postCsv[:,-1]) ]
print(ruleQuest)

# for i, v in enumerate(learnQuest):
#     postCsv[postCsv[:,-2] == v, -2] = i

for i, j in zip([-2,-1], [learnQuest,ruleQuest]):
    postCsv = stringToInt(postCsv, i, j)
    
print(postCsv)

# for i in range(np.shape(postCsv)[1]):
#     b,c = np.unique(postCsv[:,i], return_inverse=True)
#     print(c)
    
#b, c = np.unique(a, return_inverse=True)
#c+1

[[b'0' b'0' b'2' b'7' b'5' b'5' b'9' b'gradual' b'yes-rule']
 [b'0' b'1' b'1' b'6' b'1' b'4' b'10' b'insight' b'yes-rule']
 [b'0' b'2' b'0' b'6' b'1' b'4' b'10' b'insight' b'yes-rule']
 [b'0' b'3' b'3' b'9' b'10' b'7' b'2' b'none' b'unsure']
 [b'1' b'0' b'3' b'10' b'10' b'10' b'1' b'none' b'unsure']
 [b'1' b'1' b'1' b'5' b'4' b'4' b'10' b'insight' b'yes-rule']
 [b'1' b'2' b'2' b'9' b'9' b'10' b'10' b'insight' b'yes-rule']
 [b'1' b'3' b'0' b'2' b'1' b'3' b'10' b'insight' b'yes-rule']
 [b'2' b'0' b'0' b'5' b'3' b'2' b'8' b'gradual' b'yes-rule']
 [b'2' b'1' b'3' b'8' b'8' b'9' b'2' b'none' b'unsure']
 [b'2' b'2' b'2' b'5' b'3' b'3' b'9' b'gradual' b'yes-rule']
 [b'2' b'3' b'1' b'4' b'3' b'2' b'7' b'gradual' b'yes-rule']
 [b'3' b'0' b'2' b'7' b'7' b'3' b'8' b'gradual' b'unsure']
 [b'3' b'1' b'3' b'9' b'10' b'9' b'2' b'gradual' b'no-rule']
 [b'3' b'2' b'0' b'6' b'2' b'2' b'10' b'insight' b'yes-rule']
 [b'3' b'3' b'1' b'4' b'6' b'4' b'8' b'insight' b'yes-rule']
 [b'4' b'0' b'0' b'9' b'1' b'4

In [15]:
USERS = 5
float_formatter = lambda x: "%.2f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})
np.set_printoptions(precision=2)

metricsUser = np.asarray(metricsUser, dtype='float')
postCsv = postCsv.astype('float')
# Order by first column (id) and then by third column (category task complexity)
postCsv = postCsv[np.lexsort((postCsv[:,2], postCsv[:,0]))]

# user, category task (complexity), #times task selected, % selection, #times correct on this task, % correct
print(metricsUser)
metricsUser = metricsUser.reshape(USERS*TASKS,6)
print(metricsUser)
# user, monster id, category task (complexity), answers for that category
print(postCsv)

print(np.shape(metricsUser), np.shape(postCsv))

# Check that columns (user and task category complexity) are the same in order to fusion them
if np.array_equal(metricsUser[:,0], postCsv[:,0]) and np.array_equal(metricsUser[:,1], postCsv[:,2]):
    finalStats = np.hstack((metricsUser, postCsv[:,3:]))
    print(finalStats)
else:
    print('columns do not match, someone did not select all tasks')

[[[  0.00e+00   0.00e+00   8.90e+01   1.91e-01   6.70e+01   7.53e-01]
  [  0.00e+00   1.00e+00   9.00e+01   1.93e-01   7.40e+01   8.22e-01]
  [  0.00e+00   2.00e+00   1.53e+02   3.28e-01   1.12e+02   7.32e-01]
  [  0.00e+00   3.00e+00   1.35e+02   2.89e-01   6.90e+01   5.11e-01]]

 [[  1.00e+00   0.00e+00   4.90e+01   1.32e-01   4.40e+01   8.98e-01]
  [  1.00e+00   1.00e+00   3.20e+01   8.65e-02   2.80e+01   8.75e-01]
  [  1.00e+00   2.00e+00   1.82e+02   4.92e-01   1.27e+02   6.98e-01]
  [  1.00e+00   3.00e+00   1.07e+02   2.89e-01   4.40e+01   4.11e-01]]

 [[  2.00e+00   0.00e+00   4.60e+01   1.87e-01   2.70e+01   5.87e-01]
  [  2.00e+00   1.00e+00   2.30e+01   9.35e-02   1.60e+01   6.96e-01]
  [  2.00e+00   2.00e+00   5.10e+01   2.07e-01   2.60e+01   5.10e-01]
  [  2.00e+00   3.00e+00   1.26e+02   5.12e-01   5.70e+01   4.52e-01]]

 [[  3.00e+00   0.00e+00   2.10e+01   7.81e-02   2.00e+01   9.52e-01]
  [  3.00e+00   1.00e+00   4.70e+01   1.75e-01   3.10e+01   6.60e-01]
  [  3.00e+00 

In [16]:
np.savetxt('fpilot.txt', finalStats)

In [9]:
te = np.loadtxt('fpilot.txt')
te

array([[  0.00e+00,   0.00e+00,   8.90e+01,   1.91e-01,   6.70e+01,
          7.53e-01,   6.00e+00,   1.00e+00,   4.00e+00,   1.00e+01,
          1.00e+00,   2.00e+00],
       [  0.00e+00,   1.00e+00,   1.53e+02,   3.28e-01,   1.12e+02,
          7.32e-01,   7.00e+00,   5.00e+00,   5.00e+00,   9.00e+00,
          0.00e+00,   2.00e+00],
       [  0.00e+00,   2.00e+00,   9.00e+01,   1.93e-01,   7.40e+01,
          8.22e-01,   6.00e+00,   1.00e+00,   4.00e+00,   1.00e+01,
          1.00e+00,   2.00e+00],
       [  0.00e+00,   3.00e+00,   1.35e+02,   2.89e-01,   6.90e+01,
          5.11e-01,   9.00e+00,   1.00e+01,   7.00e+00,   2.00e+00,
          2.00e+00,   1.00e+00],
       [  1.00e+00,   0.00e+00,   4.90e+01,   1.32e-01,   4.40e+01,
          8.98e-01,   2.00e+00,   1.00e+00,   3.00e+00,   1.00e+01,
          1.00e+00,   2.00e+00],
       [  1.00e+00,   1.00e+00,   1.82e+02,   4.92e-01,   1.27e+02,
          6.98e-01,   9.00e+00,   9.00e+00,   1.00e+01,   1.00e+01,
          1.00e+00,