In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rcParams
import pandas as pd
import warnings

from ipywidgets import widgets
from IPython.html.widgets import *

warnings.filterwarnings('ignore')
rcParams.update({'font.size': 15})
#plt.style.use('ggplot')
#plt.style.use('seaborn-dark-palette')
plt.style.use('fivethirtyeight')

/usr/lib/python3.6/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)


In [13]:
#bear, bunny, green, squid

TASKS = 4
USERS = 5
PHASE = 'exploration'


def stringToInt(arr, position, values):
    for i, v in enumerate(values):
        arr[arr[:,position] == v, position] = i
    return arr


csvFile = '../data/test2.csv'
csvFile = '../data/monsters_data_pilot_050317.csv'
csv = np.genfromtxt(csvFile, dtype=np.string_, delimiter=',', usecols=(0,1,6,7,10), skip_header=1)

#print(csv)

# Get monster type
monsters = [m for m in np.unique(csv[:,2])]
# Get category
#categories = [c for c in np.unique(csv[:,3])]
categories = [b'category1D', b'categoryIgnore1D', b'category2D', b'categoryRandom']
# Get ids
ids = [i for i in np.unique(csv[:,0]) ]
# Get unique phases
phases = [p for p in np.unique(csv[:,1]) ]
# For converting string to int boolean
bo = [b'False', b'True']

csvInt = csv.copy()
# Convert fields to ints for easy processing
for i,j in enumerate([ids, phases, monsters, categories, bo]):
    csvInt = stringToInt(csvInt, i, j)
csvInt = csvInt.astype('int')

#print(csvInt)

#[b'free', b'test', b'train']
exploration, test, train = 0, 1, 2
if PHASE == 'exploration': 
    # Get only those in free exploration phase
    csvInt = csvInt[csvInt[:,1]==test]
    csvInt = np.delete(csvInt, 1, axis=1)

# Split by user
splitCsv = [csvInt[csvInt[:,0]==i] for i in np.unique(csvInt[:,0])]



# Count times correct per task, times task chosen, % for both
metricsUser = []

if PHASE == 'exploration':
    # id, monster, category, success
    for user in range(np.shape(splitCsv)[0]):
        questions = splitCsv[user]
        print(questions)
        # Count number of times a task was selected
        task, ctask = np.unique(questions[:,2], return_counts=True)
        print(task, ctask, ctask/np.shape(questions)[0])

        metricsTask = []
        # Count number of times the answer was correct per task and percent
        for t in range(TASKS):
            correct = np.sum(questions[questions[:,2] == t,3] == 1) 
            total = np.sum(questions[:,2] == t)
            if t in task:
                # Task category, times task selected, % selection, #times correct on this task, % correct
                metricsTask.append([user, t, ctask[np.where(task==t)][0], ctask[np.where(task==t)][0]/np.shape(questions)[0], correct, np.nan_to_num(correct/total)])
                #print(t, ctask[np.where(task==t)][0], ctask[np.where(task==t)][0]/np.shape(questions)[0], correct, np.nan_to_num(correct/total) )
            else:
                metricsTask.append([user, t, 0., 0., correct, np.nan_to_num(correct/total)])
                #print(t, 0, 0, correct, np.nan_to_num(correct/total))

        metricsUser.append(metricsTask)

print(monsters, categories)
print(metricsUser)


[[0 1 3 1]
 [0 1 3 1]
 [0 1 3 1]
 [0 1 3 0]
 [0 1 3 0]
 [0 1 3 1]
 [0 1 3 1]
 [0 1 3 0]
 [0 1 3 1]
 [0 1 3 0]
 [0 1 3 0]
 [0 1 3 0]
 [0 1 3 1]
 [0 1 3 0]
 [0 1 3 0]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 0]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 0]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 1]
 [0 2 0 0]
 [0 2 0 1]
 [0 2 0 1]
 [0 0 2 1]
 [0 0 2 0]
 [0 0 2 1]
 [0 0 2 1]
 [0 0 2 0]
 [0 0 2 1]
 [0 0 2 1]
 [0 0 2 1]
 [0 0 2 0]
 [0 0 2 0]
 [0 0 2 1]
 [0 0 2 0]
 [0 0 2 1]
 [0 0 2 1]
 [0 0 2 0]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]
 [0 3 1 1]]
[0 1 2 3] [15 15 15 15] [ 0.25  0.25  0.25  0.25]
[[1 2 1 1]
 [1 2 1 1]
 [1 2 1 0]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 0]
 [1 2 1 1]
 [1 2 1 0]
 [1 2 1 0]
 [1 2 1 0]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]
 [1 2 1 1]
 [1 1 3 0]
 [1 1 3 1]
 [1 1 3 0]
 [1 1 3 0]
 [1 1 3 0]
 [1 1 3 0]
 [1 1 3 1]
 [1 1 3 1]
 [1 1 3 0]
 [1 1 3 0]
 [1 1 3 0]
 [1

In [14]:
# participant:assignmentId,interested-Bear,complex-Bear,time-Bear,progress-Bear,learning-Bear,
# rule-Bear,interested-Bunny,complex-Bunny,time-Bunny,progress-Bunny,learning-Bunny,rule-Bunny,
# interested-GreenMonster,complex-GreenMonster,time-GreenMonster,progress-GreenMonster,learning-GreenMonster,
# rule-GreenMonster,interested-Squid,complex-Squid,time-Squid,progress-Squid,learning-Squid,rule-Squid,age,
# gender,race,ethnicity,thoughts,comments

#bear 1:6
#bunny 7:12
#greenm 13:18
#squid 19:24

# Subjective data
csvFile = '../data/monsters_extra_data_pilot_050317.csv'
scsv = np.genfromtxt(csvFile, dtype=np.string_, delimiter=',', skip_header=1)#usecols=(0,5,6,9), skip_header=1)
print(scsv[1])

#Reorder them according to the actual categories
print(monsters, categories)

postCsv = []
for user in range(np.shape(splitCsv)[0]):
    questions = splitCsv[user][:,1:3]
    postQ = scsv[user]
    _, mIdx = np.unique(questions[:,0], return_index=True)
    _, cIdx = np.unique(questions[:,0], return_index=True)
    print(questions[np.sort(mIdx),0])
    print(questions[np.sort(cIdx),1])
    # stack monster type, complexity type
    moncat = np.vstack((questions[np.sort(mIdx),0], questions[np.sort(cIdx),1])).T
    moncat = moncat[moncat[:,0].argsort()]
    print(moncat)
    for n, mon in enumerate(moncat[:,0]):
        answ = postQ[n*6+1:6*(n+1)+1]
        # stack user id, monster id, category id, answers for that category
        print(np.hstack((user, mon, moncat[n,1], answ.tolist())))
        postCsv.append(np.hstack((user, mon, moncat[n,1], answ.tolist())).tolist())
    print(questions)
print(postCsv)

[b'A1DWDCD4CHM68O:379J5II41PVBT47GLIG7MAOG0ALEL7' b'9' b'3' b'9' b'10'
 b'10' b'gradual' b'9' b'7' b'2' b'3' b'2' b'none' b'8' b'10' b'3' b'3'
 b'4' b'insight' b'9' b'7' b'2' b'5' b'10' b'insight' b'26' b'male'
 b'white' b'nonhisp' b'How people pay attention to small detail changes'
 b'']
[b'Bear', b'Bunny', b'GreenMonster', b'Squid'] [b'category1D', b'categoryIgnore1D', b'category2D', b'categoryRandom']
[1 2 0 3]
[3 0 2 1]
[[0 2]
 [1 3]
 [2 0]
 [3 1]]
[b'0' b'0' b'2' b'6' b'7' b'4' b'5' b'9' b'none']
[b'0' b'1' b'3' b'9' b'10' b'9' b'3' b'9' b'none']
[b'0' b'2' b'0' b'4' b'3' b'3' b'7' b'10' b'gradual']
[b'0' b'3' b'1' b'2' b'1' b'7' b'10' b'10' b'gradual']
[[1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [1 3]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [2 0]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [3 1]
 [3 1]
 [3 

In [15]:
postCsv = np.asarray(postCsv)
print(postCsv)
print(np.shape(postCsv))

learnQuest = [i for i in np.unique(postCsv[:,-1]) ]
#ruleQuest = [i for i in np.unique(postCsv[:,-2]) ]

#for i, j in zip([-1,-2], [learnQuest,ruleQuest]):
#    postCsv = stringToInt(postCsv, i, j)

postCsv = stringToInt(postCsv, -1, learnQuest)
    
print(postCsv)

# for i in range(np.shape(postCsv)[1]):
#     b,c = np.unique(postCsv[:,i], return_inverse=True)
#     print(c)
    
#b, c = np.unique(a, return_inverse=True)
#c+1

[[b'0' b'0' b'2' b'6' b'7' b'4' b'5' b'9' b'none']
 [b'0' b'1' b'3' b'9' b'10' b'9' b'3' b'9' b'none']
 [b'0' b'2' b'0' b'4' b'3' b'3' b'7' b'10' b'gradual']
 [b'0' b'3' b'1' b'2' b'1' b'7' b'10' b'10' b'gradual']
 [b'1' b'0' b'0' b'9' b'3' b'9' b'10' b'10' b'gradual']
 [b'1' b'1' b'3' b'9' b'7' b'2' b'3' b'2' b'none']
 [b'1' b'2' b'1' b'8' b'10' b'3' b'3' b'4' b'insight']
 [b'1' b'3' b'2' b'9' b'7' b'2' b'5' b'10' b'insight']
 [b'2' b'0' b'1' b'8' b'1' b'3' b'8' b'10' b'insight']
 [b'2' b'1' b'0' b'7' b'1' b'3' b'8' b'10' b'insight']
 [b'2' b'2' b'2' b'2' b'10' b'7' b'3' b'5' b'unsure']
 [b'2' b'3' b'3' b'2' b'10' b'7' b'3' b'5' b'unsure']
 [b'3' b'0' b'3' b'4' b'7' b'6' b'6' b'6' b'gradual']
 [b'3' b'1' b'0' b'4' b'3' b'6' b'6' b'6' b'gradual']
 [b'3' b'2' b'2' b'4' b'4' b'6' b'6' b'6' b'gradual']
 [b'3' b'3' b'1' b'4' b'6' b'6' b'6' b'6' b'gradual']
 [b'4' b'0' b'3' b'10' b'10' b'10' b'1' b'1' b'none']
 [b'4' b'1' b'1' b'1' b'1' b'1' b'10' b'10' b'insight']
 [b'4' b'2' b'2' b'10' b'

In [16]:
USERS = 5
float_formatter = lambda x: "%.2f" % x
np.set_printoptions(formatter={'float_kind':float_formatter})
np.set_printoptions(precision=2)

metricsUser = np.asarray(metricsUser, dtype='float')
postCsv = postCsv.astype('float')
# Order by first column (id) and then by third column (category task complexity)
postCsv = postCsv[np.lexsort((postCsv[:,2], postCsv[:,0]))]

# user, category task (complexity), #times task selected, % selection, #times correct on this task, % correct
print(metricsUser)
metricsUser = metricsUser.reshape(USERS*TASKS,6)
print(metricsUser)
# user, monster id, category task (complexity), answers for that category
print(postCsv)

print(np.shape(metricsUser), np.shape(postCsv))

# Check that columns (user and task category complexity) are the same in order to fusion them
if np.array_equal(metricsUser[:,0], postCsv[:,0]) and np.array_equal(metricsUser[:,1], postCsv[:,2]):
    finalStats = np.hstack((metricsUser, postCsv[:,3:]))
    print(finalStats)
else:
    print('columns do not match, someone did not select all tasks')

[[[  0.     0.    15.     0.25  12.     0.8 ]
  [  0.     1.    15.     0.25  15.     1.  ]
  [  0.     2.    15.     0.25   9.     0.6 ]
  [  0.     3.    15.     0.25   7.     0.47]]

 [[  1.     0.    15.     0.25  12.     0.8 ]
  [  1.     1.    15.     0.25  10.     0.67]
  [  1.     2.    15.     0.25  11.     0.73]
  [  1.     3.    15.     0.25   4.     0.27]]

 [[  2.     0.    15.     0.25  15.     1.  ]
  [  2.     1.    15.     0.25  14.     0.93]
  [  2.     2.    15.     0.25   6.     0.4 ]
  [  2.     3.    15.     0.25  10.     0.67]]

 [[  3.     0.    15.     0.25  10.     0.67]
  [  3.     1.    15.     0.25  11.     0.73]
  [  3.     2.    15.     0.25   7.     0.47]
  [  3.     3.    15.     0.25   8.     0.53]]

 [[  4.     0.    15.     0.25  15.     1.  ]
  [  4.     1.    15.     0.25  13.     0.87]
  [  4.     2.    15.     0.25  13.     0.87]
  [  4.     3.    15.     0.25   6.     0.4 ]]]
[[  0.     0.    15.     0.25  12.     0.8 ]
 [  0.     1.    15.     

In [17]:
#np.savetxt('spilot-train.txt', finalStats)
np.savetxt('spilot-test.txt', finalStats)

#np.savetxt('spilot-free.txt', metricsUser)

In [7]:
metricsUser

array([[  0.00e+00,   0.00e+00,   2.90e+01,   1.16e-01,   2.50e+01,
          8.62e-01],
       [  0.00e+00,   1.00e+00,   8.70e+01,   3.48e-01,   8.10e+01,
          9.31e-01],
       [  0.00e+00,   2.00e+00,   3.30e+01,   1.32e-01,   1.80e+01,
          5.45e-01],
       [  0.00e+00,   3.00e+00,   1.01e+02,   4.04e-01,   5.10e+01,
          5.05e-01],
       [  1.00e+00,   0.00e+00,   2.50e+02,   1.00e+00,   2.14e+02,
          8.56e-01],
       [  1.00e+00,   1.00e+00,   0.00e+00,   0.00e+00,   0.00e+00,
          0.00e+00],
       [  1.00e+00,   2.00e+00,   0.00e+00,   0.00e+00,   0.00e+00,
          0.00e+00],
       [  1.00e+00,   3.00e+00,   0.00e+00,   0.00e+00,   0.00e+00,
          0.00e+00],
       [  2.00e+00,   0.00e+00,   3.30e+01,   1.32e-01,   2.70e+01,
          8.18e-01],
       [  2.00e+00,   1.00e+00,   8.80e+01,   3.52e-01,   7.40e+01,
          8.41e-01],
       [  2.00e+00,   2.00e+00,   3.60e+01,   1.44e-01,   1.90e+01,
          5.28e-01],
       [  2.00e+00,  